/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yuil;

import com.menu.MenuGroup;
import com.util.Prompt;

public class App {

    Prompt prompt = new Prompt(System.in);
    MenuGroup mainMenu;

    App() {

    }

    public static void main(String[] args) {
        System.out.println("[정육 관리 시스템]");
    }

    void prepareMenu() {
        mainMenu = MenuGroup.getInstance("메인");
        MenuGroup infoMenu  = mainMenu.addGroup("판매 상품 정보");


        MenuGroup orderMenu = mainMenu.addGroup("주문 관리");


        MenuGroup stockMenu = mainMenu.addGroup("재고 관리");
    }


}
