DROP TABLE IF EXISTS `Untitled`;

CREATE TABLE `Untitled` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field15`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled2`;

CREATE TABLE `Untitled2` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `Untitled3`;

CREATE TABLE `Untitled3` (
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled4`;

CREATE TABLE `Untitled4` (
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled5`;

CREATE TABLE `Untitled5` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled6`;

CREATE TABLE `Untitled6` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled7`;

CREATE TABLE `Untitled7` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled8`;

CREATE TABLE `Untitled8` (
	`Key52`	VARCHAR(255)	NOT NULL,
	`Key3`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled9`;

CREATE TABLE `Untitled9` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key3`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL,
	`Field7`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled10`;

CREATE TABLE `Untitled10` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled12`;

CREATE TABLE `Untitled12` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled13`;

CREATE TABLE `Untitled13` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled14`;

CREATE TABLE `Untitled14` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key3`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled15`;

CREATE TABLE `Untitled15` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled16`;

CREATE TABLE `Untitled16` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key3`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled17`;

CREATE TABLE `Untitled17` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field15`	VARCHAR(255)	NULL,
	`Key3`	VARCHAR(255)	NOT NULL,
	`Key4`	VARCHAR(255)	NOT NULL,
	`Key5`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `Untitled18`;

CREATE TABLE `Untitled18` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `Untitled19`;

CREATE TABLE `Untitled19` (
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key`	VARCHAR(255)	NOT NULL,
	`Key3`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled20`;

CREATE TABLE `Untitled20` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `Untitled21`;

CREATE TABLE `Untitled21` (
	`Key`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `Untitled22`;

CREATE TABLE `Untitled22` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Key2`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `Untitled23`;

CREATE TABLE `Untitled23` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key3`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled24`;

CREATE TABLE `Untitled24` (
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key`	VARCHAR(255)	NOT NULL,
	`Field7`	VARCHAR(255)	NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field8`	VARCHAR(255)	NULL,
	`Field9`	VARCHAR(255)	NULL,
	`Field10`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled25`;

CREATE TABLE `Untitled25` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled26`;

CREATE TABLE `Untitled26` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field3`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `CopyOfUntitled15`;

CREATE TABLE `CopyOfUntitled15` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key3`	VARCHAR(255)	NOT NULL,
	`Key4`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `Untitled28`;

CREATE TABLE `Untitled28` (
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `Untitled32`;

CREATE TABLE `Untitled32` (
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled29`;

CREATE TABLE `Untitled29` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled31`;

CREATE TABLE `Untitled31` (
	`Key`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `Untitled11`;

CREATE TABLE `Untitled11` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled27`;

CREATE TABLE `Untitled27` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled30`;

CREATE TABLE `Untitled30` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled33`;

CREATE TABLE `Untitled33` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL,
	`Field7`	VARCHAR(255)	NULL,
	`Field8`	VARCHAR(255)	NULL,
	`Field9`	VARCHAR(255)	NULL,
	`Field10`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled34`;

CREATE TABLE `Untitled34` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL,
	`Field7`	VARCHAR(255)	NULL,
	`Field8`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled35`;

CREATE TABLE `Untitled35` (
	`Key5`	VARCHAR(255)	NOT NULL,
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key3`	VARCHAR(255)	NOT NULL,
	`Key4`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `Untitled36`;

CREATE TABLE `Untitled36` (
	`Key`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `CopyOfUntitled5`;

CREATE TABLE `CopyOfUntitled5` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Key52`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled37`;

CREATE TABLE `Untitled37` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

ALTER TABLE `Untitled` ADD CONSTRAINT `PK_UNTITLED` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled2` ADD CONSTRAINT `PK_UNTITLED2` PRIMARY KEY (
	`Key`,
	`Key2`
);

ALTER TABLE `Untitled3` ADD CONSTRAINT `PK_UNTITLED3` PRIMARY KEY (
	`Key2`
);

ALTER TABLE `Untitled4` ADD CONSTRAINT `PK_UNTITLED4` PRIMARY KEY (
	`Key2`
);

ALTER TABLE `Untitled5` ADD CONSTRAINT `PK_UNTITLED5` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled6` ADD CONSTRAINT `PK_UNTITLED6` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled8` ADD CONSTRAINT `PK_UNTITLED8` PRIMARY KEY (
	`Key52`
);

ALTER TABLE `Untitled9` ADD CONSTRAINT `PK_UNTITLED9` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled10` ADD CONSTRAINT `PK_UNTITLED10` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled12` ADD CONSTRAINT `PK_UNTITLED12` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled13` ADD CONSTRAINT `PK_UNTITLED13` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled14` ADD CONSTRAINT `PK_UNTITLED14` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled15` ADD CONSTRAINT `PK_UNTITLED15` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled16` ADD CONSTRAINT `PK_UNTITLED16` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled17` ADD CONSTRAINT `PK_UNTITLED17` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled19` ADD CONSTRAINT `PK_UNTITLED19` PRIMARY KEY (
	`Key2`
);

ALTER TABLE `Untitled21` ADD CONSTRAINT `PK_UNTITLED21` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled22` ADD CONSTRAINT `PK_UNTITLED22` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled23` ADD CONSTRAINT `PK_UNTITLED23` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled24` ADD CONSTRAINT `PK_UNTITLED24` PRIMARY KEY (
	`Key2`
);

ALTER TABLE `Untitled25` ADD CONSTRAINT `PK_UNTITLED25` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled26` ADD CONSTRAINT `PK_UNTITLED26` PRIMARY KEY (
	`Key`,
	`Key2`
);

ALTER TABLE `CopyOfUntitled15` ADD CONSTRAINT `PK_COPYOFUNTITLED15` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled28` ADD CONSTRAINT `PK_UNTITLED28` PRIMARY KEY (
	`Key2`
);

ALTER TABLE `Untitled32` ADD CONSTRAINT `PK_UNTITLED32` PRIMARY KEY (
	`Key2`
);

ALTER TABLE `Untitled29` ADD CONSTRAINT `PK_UNTITLED29` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled31` ADD CONSTRAINT `PK_UNTITLED31` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled11` ADD CONSTRAINT `PK_UNTITLED11` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled27` ADD CONSTRAINT `PK_UNTITLED27` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled30` ADD CONSTRAINT `PK_UNTITLED30` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled33` ADD CONSTRAINT `PK_UNTITLED33` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled34` ADD CONSTRAINT `PK_UNTITLED34` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled35` ADD CONSTRAINT `PK_UNTITLED35` PRIMARY KEY (
	`Key5`
);

ALTER TABLE `Untitled36` ADD CONSTRAINT `PK_UNTITLED36` PRIMARY KEY (
	`Key`
);

ALTER TABLE `CopyOfUntitled5` ADD CONSTRAINT `PK_COPYOFUNTITLED5` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled37` ADD CONSTRAINT `PK_UNTITLED37` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled2` ADD CONSTRAINT `FK_Untitled_TO_Untitled2_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled2` ADD CONSTRAINT `FK_Untitled29_TO_Untitled2_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled29` (
	`Key`
);

ALTER TABLE `Untitled3` ADD CONSTRAINT `FK_Untitled_TO_Untitled3_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled4` ADD CONSTRAINT `FK_Untitled3_TO_Untitled4_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled3` (
	`Key2`
);

ALTER TABLE `Untitled5` ADD CONSTRAINT `FK_Untitled3_TO_Untitled5_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled3` (
	`Key2`
);

ALTER TABLE `Untitled6` ADD CONSTRAINT `FK_Untitled_TO_Untitled6_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled7` ADD CONSTRAINT `FK_Untitled_TO_Untitled7_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled8` ADD CONSTRAINT `FK_Untitled35_TO_Untitled8_1` FOREIGN KEY (
	`Key52`
)
REFERENCES `Untitled35` (
	`Key5`
);

ALTER TABLE `Untitled8` ADD CONSTRAINT `FK_Untitled10_TO_Untitled8_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `Untitled10` (
	`Key`
);

ALTER TABLE `Untitled9` ADD CONSTRAINT `FK_Untitled12_TO_Untitled9_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled12` (
	`Key`
);

ALTER TABLE `Untitled9` ADD CONSTRAINT `FK_Untitled_TO_Untitled9_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled13` ADD CONSTRAINT `FK_Untitled9_TO_Untitled13_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled9` (
	`Key`
);

ALTER TABLE `Untitled14` ADD CONSTRAINT `FK_Untitled9_TO_Untitled14_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled9` (
	`Key`
);

ALTER TABLE `Untitled14` ADD CONSTRAINT `FK_Untitled_TO_Untitled14_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled15` ADD CONSTRAINT `FK_CopyOfUntitled15_TO_Untitled15_1` FOREIGN KEY (
	`Key`
)
REFERENCES `CopyOfUntitled15` (
	`Key`
);

ALTER TABLE `Untitled16` ADD CONSTRAINT `FK_Untitled14_TO_Untitled16_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled14` (
	`Key`
);

ALTER TABLE `Untitled16` ADD CONSTRAINT `FK_Untitled_TO_Untitled16_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled17` ADD CONSTRAINT `FK_Untitled_TO_Untitled17_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled17` ADD CONSTRAINT `FK_Untitled11_TO_Untitled17_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `Untitled11` (
	`Key`
);

ALTER TABLE `Untitled17` ADD CONSTRAINT `FK_Untitled27_TO_Untitled17_1` FOREIGN KEY (
	`Key4`
)
REFERENCES `Untitled27` (
	`Key`
);

ALTER TABLE `Untitled17` ADD CONSTRAINT `FK_Untitled37_TO_Untitled17_1` FOREIGN KEY (
	`Key5`
)
REFERENCES `Untitled37` (
	`Key`
);

ALTER TABLE `Untitled18` ADD CONSTRAINT `FK_Untitled17_TO_Untitled18_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled17` (
	`Key`
);

ALTER TABLE `Untitled18` ADD CONSTRAINT `FK_Untitled_TO_Untitled18_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled19` ADD CONSTRAINT `FK_Untitled17_TO_Untitled19_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled17` (
	`Key`
);

ALTER TABLE `Untitled19` ADD CONSTRAINT `FK_Untitled_TO_Untitled19_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled19` ADD CONSTRAINT `FK_Untitled31_TO_Untitled19_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `Untitled31` (
	`Key`
);

ALTER TABLE `Untitled20` ADD CONSTRAINT `FK_Untitled17_TO_Untitled20_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled17` (
	`Key`
);

ALTER TABLE `Untitled20` ADD CONSTRAINT `FK_Untitled21_TO_Untitled20_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled21` (
	`Key`
);

ALTER TABLE `Untitled22` ADD CONSTRAINT `FK_Untitled17_TO_Untitled22_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled17` (
	`Key`
);

ALTER TABLE `Untitled23` ADD CONSTRAINT `FK_Untitled17_TO_Untitled23_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `Untitled17` (
	`Key`
);

ALTER TABLE `Untitled23` ADD CONSTRAINT `FK_Untitled_TO_Untitled23_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled24` ADD CONSTRAINT `FK_Untitled23_TO_Untitled24_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled23` (
	`Key`
);

ALTER TABLE `Untitled24` ADD CONSTRAINT `FK_Untitled36_TO_Untitled24_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled36` (
	`Key`
);

ALTER TABLE `Untitled25` ADD CONSTRAINT `FK_Untitled23_TO_Untitled25_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled23` (
	`Key`
);

ALTER TABLE `Untitled26` ADD CONSTRAINT `FK_Untitled23_TO_Untitled26_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled23` (
	`Key`
);

ALTER TABLE `CopyOfUntitled15` ADD CONSTRAINT `FK_Untitled14_TO_CopyOfUntitled15_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled14` (
	`Key`
);

ALTER TABLE `CopyOfUntitled15` ADD CONSTRAINT `FK_Untitled9_TO_CopyOfUntitled15_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `Untitled9` (
	`Key`
);

ALTER TABLE `CopyOfUntitled15` ADD CONSTRAINT `FK_Untitled16_TO_CopyOfUntitled15_1` FOREIGN KEY (
	`Key4`
)
REFERENCES `Untitled16` (
	`Key`
);

ALTER TABLE `Untitled28` ADD CONSTRAINT `FK_Untitled23_TO_Untitled28_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled23` (
	`Key`
);

ALTER TABLE `Untitled28` ADD CONSTRAINT `FK_Untitled17_TO_Untitled28_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled17` (
	`Key`
);

ALTER TABLE `Untitled32` ADD CONSTRAINT `FK_Untitled28_TO_Untitled32_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled28` (
	`Key2`
);

ALTER TABLE `Untitled30` ADD CONSTRAINT `FK_Untitled26_TO_Untitled30_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled26` (
	`Key`
);

ALTER TABLE `Untitled33` ADD CONSTRAINT `FK_Untitled_TO_Untitled33_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled33` ADD CONSTRAINT `FK_Untitled11_TO_Untitled33_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled11` (
	`Key`
);

ALTER TABLE `Untitled34` ADD CONSTRAINT `FK_Untitled17_TO_Untitled34_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled17` (
	`Key`
);

ALTER TABLE `Untitled35` ADD CONSTRAINT `FK_Untitled_TO_Untitled35_1` FOREIGN KEY (
	`Key`
)
REFERENCES `Untitled` (
	`Key`
);

ALTER TABLE `Untitled35` ADD CONSTRAINT `FK_Untitled9_TO_Untitled35_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled9` (
	`Key`
);

ALTER TABLE `Untitled35` ADD CONSTRAINT `FK_Untitled14_TO_Untitled35_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `Untitled14` (
	`Key`
);

ALTER TABLE `Untitled35` ADD CONSTRAINT `FK_Untitled16_TO_Untitled35_1` FOREIGN KEY (
	`Key4`
)
REFERENCES `Untitled16` (
	`Key`
);

ALTER TABLE `CopyOfUntitled5` ADD CONSTRAINT `FK_Untitled8_TO_CopyOfUntitled5_1` FOREIGN KEY (
	`Key52`
)
REFERENCES `Untitled8` (
	`Key52`
);

